name: PokerHands Assignment - Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
# name of the job
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build
        
      - name: Run the tests
        run: dotnet test --logger "console;verbosity=detailed"
